before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: l9qVGTVx1+hNeHttOraQ50yJT0sFD39j/T8s+rJFN4RkqbrutqmNwoEb4MwkmZHbTiahzgx4hr+KbgP9tIztePYYIT1fL/RktOIarxemDKC8oeF81GOzosbxeZ5hx+aa4TznrNESkWzfvmVNM5/7gp3j0IcvfW7PmOxFRZwyUI51eWwEEKpEYt8VpuU4n4FpjB44tcu+NTgvyx7AqKRCr+pT3tfBxtszn6evwe/aMPHJkCCKxL5UuRiPuqiqbiw/I8R2eDqO1TxuPEfPgjQCnTgoB7M1dlYeR/3dDpFdln2bXLhGo6DpyDfXB0k5U3WpHJqxjCp7GhOWRYxMli218HCEFYrY24+z4nyqzPZa4vz1eq8nDYQCGVpaRILfgWNkHgQOxwi+ktD3htYwFp++KwOyTQSqUhpMH3cUIsoh7PohDKngyzB4pU81J4b8jrbi72vDr3d4FlT/bT8Yee3Mu/dwq2c97cd1O3mCqt9w6i8ZzGpFCsJroQBk5LL/9ly6iASiA9/1hFffnMQfObGauo6ZCVYFmprXRxUxKZMdX3plk1LoGn7OegYDuTWtrmJRKCvG83QTPfEyNvqBl690IRCHGyIdcvmLWpCHzkBDaP2wGsVIZrZc9GQH9vkN6wVUEIzOm6gs/fm3ORbxVJCVuqerAGi8zXD3Y9jI1j7n1mw= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
